#!/usr/bin/env bash

#set -x
#set -euxo pipefail

declare -r prog=$(basename "$0")
declare -r endpoint=https://api.autodns.com/v1
declare -r ttl=120

if [ -f '~/.autodns-cli.rc' ]; then
    # shellcheck disable=SC1091
    source ~/.autodns-cli.rc
fi

#source ./func.sh
#source ./commands.sh

source $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/func.sh
source $( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )/commands.sh

subcommand=$1
case $subcommand in
    "" | "-h" | "--help")
        sub_help
        ;;
    *)
        shift
        declare -r command="sub_${subcommand}" 
        $command "$@"
        if [ $? = 127 ]; then
            echo "Error: '$subcommand' is not a known subcommand." >&2
            echo "       Run '${prog} --help' for a list of known subcommands." >&2
            exit 1
        fi
        ;;
esac
