version: 2

jobs:
  shell:
    docker:
      - image: koalaman/shellcheck-alpine:latest
    steps:
      - checkout
      - run:
          name: General shellcheck tests
          command: shellcheck -a -x -e SC2005,SC2155,SC2181 autodns-cli
  cli:
    docker:
      - image: graze/bats:latest
    steps:
      - checkout
      - run:
          name: Test cli commands
          command: ./tests/test-unit.sh
  unit:
    docker:
      - image: bash:3.2
    steps:
      - checkout
      - run:
          name: Run unit tests
          command: ./tests/test-unit.sh

workflows:
  version: 2
  run_all:
    jobs:
      - unit
      - cli
      - shell
